"""
02_compute_delta_z.py
---------------------
Computes the paralog upregulation metric (Δz) for every testable
significant and non-significant paralog pair.

Metric — Δz (delta z-score)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The Replogle 2022 normalized_bulk AnnData contains gemgroup
z-normalised pseudobulk expression values.  For each gene, values are
centred on the gemgroup mean (≈ baseline expression) and expressed in
standard-deviation units.

For a pair (dep_gene → paralog_gene):

    Δz = mean z-score of paralog_gene across all dep_gene KD rows
       − mean z-score of paralog_gene across all non-targeting control rows

Interpretation:
  Δz > 0 → paralog is expressed ABOVE the control baseline when dep_gene is KD'd
  Δz < 0 → paralog is expressed BELOW baseline
  Δz ≈ 0 → no change

Outputs (saved to results/{cell_line}/)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  sig_results.csv     — one row per sig pair
  nonsig_results.csv  — one row per testable non-sig direction

Usage:
    python scripts/02_compute_delta_z.py --cell-line K562
    python scripts/02_compute_delta_z.py --cell-line rpe1

    # or run all available cell lines at once:
    python scripts/02_compute_delta_z.py --all
"""

import argparse
import warnings
import numpy as np
import pandas as pd
import anndata as ad
import scipy.sparse as sp
from pathlib import Path
from tqdm import tqdm

# ── Config ────────────────────────────────────────────────────────────────────
CTRL_LABEL = "non-targeting"

ROOT      = Path(__file__).resolve().parent.parent
DATA_DIR  = ROOT / "data" / "raw"
SIG_XL    = DATA_DIR / "sig_37_paralog.xlsx"
NONSIG_XL = DATA_DIR / "non_sig_paralog.xlsx"

# Map cell-line name → h5ad filename. Add entries here for new cell lines.
CELL_LINE_FILES = {
    "K562":           "K562_gwps_normalized_bulk_01.h5ad",
    "K562_essential": "K562_essential_pseudobulk_normalized.h5ad",  # generated by 05_preprocess.py
    "rpe1":           "rpe1_normalized_bulk_01.h5ad",
    "HCT116":         "HCT116_pseudobulk_normalized.h5ad",          # generated by 05_preprocess.py
    "HEK293T":        "HEK293T_pseudobulk_normalized.h5ad",         # generated by 05_preprocess.py
    "melanoma":       "melanoma_pseudobulk_normalized.h5ad",        # generated by 06_preprocess_gse291147.py
    "cd4t_rest":      "cd4t_rest_pseudobulk_normalized.h5ad",       # generated by 07_preprocess_cd4t.py
    "cd4t_stim8hr":   "cd4t_stim8hr_pseudobulk_normalized.h5ad",    # generated by 07_preprocess_cd4t.py
    "cd4t_stim48hr":  "cd4t_stim48hr_pseudobulk_normalized.h5ad",   # generated by 07_preprocess_cd4t.py
}

# These cell lines use obs.index directly as pert label (not Replogle's
# "{id}_{gene}_{guide}_{ensembl}" format)
DIRECT_INDEX_CELL_LINES = {
    "K562_essential", "HCT116", "HEK293T", "melanoma",
    "cd4t_rest", "cd4t_stim8hr", "cd4t_stim48hr",
}


# ── Data loading ──────────────────────────────────────────────────────────────
def load_adata(path: Path, cell_line: str):
    print(f"Loading {path.name} ...")
    adata = ad.read_h5ad(path)

    # Replogle format: obs.index = "{id}_{gene}_{guide}_{ensembl}" → parse gene
    # X-Atlas preprocessed format: obs.index = gene name directly
    if cell_line in DIRECT_INDEX_CELL_LINES:
        pert_labels = list(adata.obs.index)
    else:
        pert_labels = [idx.split("_")[1] for idx in adata.obs.index]

    X = adata.X
    if sp.issparse(X):
        X = X.toarray()
    X = np.asarray(X, dtype=np.float64)
    X[~np.isfinite(X)] = np.nan

    gene_index = {g: i for i, g in enumerate(adata.var["gene_name"])}

    n_ctrl = pert_labels.count(CTRL_LABEL)
    print(
        f"  {X.shape[0]} perturbation rows, {X.shape[1]} genes, "
        f"{n_ctrl} non-targeting control rows."
    )
    if n_ctrl == 0:
        raise ValueError(
            f"No control rows found (label='{CTRL_LABEL}'). "
            "Check CTRL_LABEL constant."
        )
    return X, pert_labels, gene_index


# ── Precompute per-perturbation mean expression ───────────────────────────────
def build_pert_mean(X: np.ndarray, pert_labels: list) -> dict[str, np.ndarray]:
    from collections import defaultdict
    rows_by_pert: dict[str, list[int]] = defaultdict(list)
    for i, label in enumerate(pert_labels):
        rows_by_pert[label].append(i)

    with warnings.catch_warnings():
        warnings.simplefilter("ignore", RuntimeWarning)
        pert_mean = {
            label: np.nanmean(X[rows, :], axis=0)
            for label, rows in rows_by_pert.items()
        }
    return pert_mean


# ── Core metric ───────────────────────────────────────────────────────────────
def delta_z(
    pert_mean: dict[str, np.ndarray],
    gene_index: dict[str, int],
    kd_gene: str,
    paralog_gene: str,
    ctrl_vec: np.ndarray,
) -> float | None:
    if kd_gene not in pert_mean:
        return None
    if paralog_gene not in gene_index:
        return None
    j = gene_index[paralog_gene]
    return float(pert_mean[kd_gene][j] - ctrl_vec[j])


# ── Per-cell-line runner ──────────────────────────────────────────────────────
def run(cell_line: str) -> None:
    h5ad = DATA_DIR / CELL_LINE_FILES[cell_line]
    if not h5ad.exists():
        print(f"[skip] {h5ad.name} not found — run 00_download_data.py first.")
        return

    results_dir = ROOT / "results" / cell_line
    results_dir.mkdir(parents=True, exist_ok=True)

    X, pert_labels, gene_index = load_adata(h5ad, cell_line)
    print("Building per-perturbation mean expression vectors ...")
    pert_mean = build_pert_mean(X, pert_labels)
    ctrl_vec  = pert_mean[CTRL_LABEL]

    # ── Significant pairs ─────────────────────────────────────────────────────
    sig = pd.read_excel(SIG_XL)
    print(f"\nComputing Δz for {len(sig)} significant pairs ...")

    sig_rows = []
    for _, row in tqdm(sig.iterrows(), total=len(sig), desc="sig pairs"):
        dz = delta_z(pert_mean, gene_index, row["dep_gene"], row["paralog_gene"], ctrl_vec)
        sig_rows.append({
            "dep_gene":             row["dep_gene"],
            "paralog_gene":         row["paralog_gene"],
            "para_pair":            row["para_pair"],
            "mean_identical_score": row["mean_identical_score"],
            "aneuploid_loss_chr":   row["aneuploid_loss_chr"],
            "paralog_chr":          row["paralog_chr"],
            "p_value_dep":          row["p_value"],
            "delta_z":              dz,
            "testable":             dz is not None,
        })

    sig_df = pd.DataFrame(sig_rows)
    sig_df.to_csv(results_dir / "sig_results.csv", index=False)
    n_testable = sig_df["testable"].sum()
    print(f"  Saved {len(sig_df)} rows ({n_testable} testable) → sig_results.csv")
    sig_test = sig_df.dropna(subset=["delta_z"])
    print(
        f"  Δz  mean={sig_test['delta_z'].mean():.4f}, "
        f"median={sig_test['delta_z'].median():.4f}, "
        f"fraction > 0: {(sig_test['delta_z'] > 0).mean():.2f}"
    )

    # ── Non-significant pairs (bidirectional) ─────────────────────────────────
    nonsig = pd.read_excel(NONSIG_XL)
    print(f"\nComputing Δz for {len(nonsig):,} non-sig pairs (bidirectional) ...")

    nonsig_rows = []
    for _, row in tqdm(nonsig.iterrows(), total=len(nonsig), desc="non-sig pairs"):
        g1, g2 = row["para_gene_1"], row["para_gene_2"]
        mid_score = row["mean_identical_score"]

        dz1 = delta_z(pert_mean, gene_index, g1, g2, ctrl_vec)
        if dz1 is not None:
            nonsig_rows.append({
                "dep_gene": g1, "paralog_gene": g2,
                "mean_identical_score": mid_score,
                "delta_z": dz1, "direction": "g1_to_g2",
            })

        dz2 = delta_z(pert_mean, gene_index, g2, g1, ctrl_vec)
        if dz2 is not None:
            nonsig_rows.append({
                "dep_gene": g2, "paralog_gene": g1,
                "mean_identical_score": mid_score,
                "delta_z": dz2, "direction": "g2_to_g1",
            })

    nonsig_df = pd.DataFrame(nonsig_rows)
    nonsig_df.to_csv(results_dir / "nonsig_results.csv", index=False)
    print(f"  Saved {len(nonsig_df):,} rows → nonsig_results.csv")

    print(f"\nDone [{cell_line}]. Run 03_compare_visualize.py --cell-line {cell_line} to generate figures.")


# ── Main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--cell-line", choices=list(CELL_LINE_FILES.keys()),
                       help="Cell line to process")
    group.add_argument("--all", action="store_true",
                       help="Process all registered cell lines")
    args = parser.parse_args()

    cell_lines = list(CELL_LINE_FILES.keys()) if args.all else [args.cell_line]
    for cl in cell_lines:
        print(f"\n{'='*60}")
        print(f"  Processing: {cl}")
        print(f"{'='*60}")
        run(cl)


if __name__ == "__main__":
    main()
